### ISSUE TITLE
make the tests pass again

### ISSUE THREAD

**Issue by bhaugen** [gopacifia/DEEP#12] opened 2016-11-11 14:26 UTC
Working on it now, this is just for communication.

**Comment by jcgarnier** [comment] 2016-11-19 14:26
Hi Bob,

I still have a problem with tests, maybe you can guide me. Here is the log output, with the error stacktraces:

/usr/bin/python2.7 /home/jc/Workspace/GoPacifia/DEEP/manage.py test
/usr/local/lib/python2.7/dist-packages/appconf/utils.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/home/jc/Workspace/GoPacifia/DEEP/account/tests/test_views.py:3: RemovedInDjango19Warning: django.utils.unittest will be removed in Django 1.9.
  from django.utils import unittest

Creating test database for alias 'default'...
Created Individual AgentType
Created Organization AgentType
Created Network AgentType
created agent types
Created Child AgentAssociationType
Created Member AgentAssociationType
Created Supplier AgentAssociationType
Created Customer AgentAssociationType
created agent association types
Created non_prod UseCase
Created rand UseCase
Created recipe UseCase
Created todo UseCase
Created cust_orders UseCase
Created purchasing UseCase
Created distribution UseCase
Created val_equation UseCase
Created payout UseCase
Created available UseCase
Created intrnl_xfer UseCase
Created supply_xfer UseCase
Created demand_xfer UseCase
created use cases
Created Citation EventType
Created Resource Consumption EventType
Created Damage EventType
Created Failed quantity EventType
Created Resource Production EventType
Created Work Provision EventType
Created Sale EventType
Created Supply EventType
Created Todo EventType
Created Resource use EventType
Created Time Contribution EventType
Created Create Changeable EventType
Created To Be Changed EventType
Created Change EventType
Created Adjust Quantity EventType
Created Distribution EventType
Created Cash Disbursement EventType
Created Payout EventType
Created Give EventType
Created Receive EventType
created event types
Created non_prod Time Contribution UseCaseEventType
Created rand Citation UseCaseEventType
Created rand Resource Consumption UseCaseEventType
Created rand Resource Production UseCaseEventType
Created rand Resource use UseCaseEventType
Created rand Time Contribution UseCaseEventType
Created rand To Be Changed UseCaseEventType
Created rand Change UseCaseEventType
Created rand Create Changeable UseCaseEventType
Created recipe Citation UseCaseEventType
Created recipe Resource Consumption UseCaseEventType
Created recipe Resource Production UseCaseEventType
Created recipe Resource use UseCaseEventType
Created recipe Time Contribution UseCaseEventType
Created recipe To Be Changed UseCaseEventType
Created recipe Change UseCaseEventType
Created recipe Create Changeable UseCaseEventType
Created todo Todo UseCaseEventType
Created distribution Distribution UseCaseEventType
Created distribution Time Contribution UseCaseEventType
Created distribution Cash Disbursement UseCaseEventType
Created val_equation Time Contribution UseCaseEventType
Created val_equation Resource Production UseCaseEventType
Created payout Payout UseCaseEventType
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created valueaccounting notice types
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
created agent types
created agent association types
created use cases
created event types
created use case event type associations
....EEEEE/home/jc/Workspace/GoPacifia/DEEP/account/views.py:239: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  "redirect_field_value": self.request.REQUEST.get(redirect_field_name),

/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py:126: RemovedInDjango19Warning: `MergeDict` is deprecated, use `dict.update()` instead.
  self._request = datastructures.MergeDict(self.POST, self.GET)

.Destroying test database for alias 'default'...
..
======================================================================
ERROR: valuenetwork.valueaccounting.tests.test_value_equations (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: valuenetwork.valueaccounting.tests.test_value_equations
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/__init__.py", line 2, in <module>
    from valuenetwork.valueaccounting.tests.test_explosions import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/test_explosions.py", line 8, in <module>
    from valuenetwork.valueaccounting.views import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/views.py", line 28, in <module>
    from valuenetwork.valueaccounting.forms import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 118, in <module>
    class AgentSelectionForm(forms.Form):
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 120, in AgentSelectionForm
    queryset=EconomicAgent.objects.individuals_without_user(),
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/models.py", line 388, in individuals_without_user
    for agent in all_agents:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: valueaccounting_economicagent


======================================================================
ERROR: valuenetwork.valueaccounting.tests.test_facets (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: valuenetwork.valueaccounting.tests.test_facets
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/__init__.py", line 2, in <module>
    from valuenetwork.valueaccounting.tests.test_explosions import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/test_explosions.py", line 8, in <module>
    from valuenetwork.valueaccounting.views import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/views.py", line 28, in <module>
    from valuenetwork.valueaccounting.forms import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 118, in <module>
    class AgentSelectionForm(forms.Form):
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 120, in AgentSelectionForm
    queryset=EconomicAgent.objects.individuals_without_user(),
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/models.py", line 388, in individuals_without_user
    for agent in all_agents:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: valueaccounting_economicagent


======================================================================
ERROR: valuenetwork.valueaccounting.tests.test_stages (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: valuenetwork.valueaccounting.tests.test_stages
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/__init__.py", line 2, in <module>
    from valuenetwork.valueaccounting.tests.test_explosions import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/test_explosions.py", line 8, in <module>
    from valuenetwork.valueaccounting.views import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/views.py", line 28, in <module>
    from valuenetwork.valueaccounting.forms import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 118, in <module>
    class AgentSelectionForm(forms.Form):
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 120, in AgentSelectionForm
    queryset=EconomicAgent.objects.individuals_without_user(),
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/models.py", line 388, in individuals_without_user
    for agent in all_agents:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: valueaccounting_economicagent


======================================================================
ERROR: valuenetwork.valueaccounting.tests.test_explosions (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: valuenetwork.valueaccounting.tests.test_explosions
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/__init__.py", line 2, in <module>
    from valuenetwork.valueaccounting.tests.test_explosions import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/test_explosions.py", line 8, in <module>
    from valuenetwork.valueaccounting.views import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/views.py", line 28, in <module>
    from valuenetwork.valueaccounting.forms import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 118, in <module>
    class AgentSelectionForm(forms.Form):
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 120, in AgentSelectionForm
    queryset=EconomicAgent.objects.individuals_without_user(),
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/models.py", line 388, in individuals_without_user
    for agent in all_agents:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: valueaccounting_economicagent


======================================================================
ERROR: valuenetwork.valueaccounting.tests.test_event_saving (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: valuenetwork.valueaccounting.tests.test_event_saving
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/__init__.py", line 2, in <module>
    from valuenetwork.valueaccounting.tests.test_explosions import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/tests/test_explosions.py", line 8, in <module>
    from valuenetwork.valueaccounting.views import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/views.py", line 28, in <module>
    from valuenetwork.valueaccounting.forms import *
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 118, in <module>
    class AgentSelectionForm(forms.Form):
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/forms.py", line 120, in AgentSelectionForm
    queryset=EconomicAgent.objects.individuals_without_user(),
  File "/home/jc/Workspace/GoPacifia/DEEP/valuenetwork/valueaccounting/models.py", line 388, in individuals_without_user
    for agent in all_agents:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: valueaccounting_economicagent


----------------------------------------------------------------------
Ran 12 tests in 0.381s

FAILED (errors=5)

Process finished with exit code 1


I made sure to update to the HEAD of the master branch.

Thank you
Jc

**Comment by bhaugen** [comment] 2016-11-19 15:35
Hi Jc, what directory are you running in? Do
```
pwd
```

**Comment by bhaugen** [comment] 2016-11-19 15:48
As I wait for a response, I'll suggest that if you see a DEEP directory in ls, do
```
cd DEEP
```
and then
```
./manage.py test
```
I'll only online off and on. Going off for a bit now. If we catch each other online at the same time, we can have a chat.

**Comment by jcgarnier** [comment] 2016-11-19 23:46
I run them from the DEEP directory.

> jc@ubik:~/Workspace/GoPacifia/DEEP$ ls
> account		  docs		holodex_script.py  manage.py		   requirements.txt	work
> cmd		  faircoin_nrp	INSTALL.md	   noenv_requirements.txt  Vagrantfile
> CONTRIBUTORS.txt  fixCAs.py	LICENSE		   pinax_utils		   valuenetwork
> Dockerfile	  fixtures	locale		   README.md		   valuenetwork.sqlite

In which timezone are you already? I'll be available most of Sunday.

**Comment by bhaugen** [comment] 2016-11-19 23:50
> In which timezone are you already? I'll be available most of Sunday.

UTC-6
What time is good for you? I can be available on request.

The directory looks good. Are you running in a virtualenv? I couldn't tell.

**Comment by bhaugen** [comment] 2016-11-20 19:47
Jc, I'm going offline for awhile. I searched on that error message unittest.loader.ModuleImportFailure and all of the cases I found seemed to be path problems.

Since I am unable to reproduce it, I think I would next want to install the repo exactly like you did, and see what happens.

**Comment by bhaugen** [comment] 2016-11-21 12:27
Reopening because Jc's problem is not yet solved.

**Comment by jcgarnier** [comment] 2016-11-21 21:25
Maybe it's due to the version of Python I use? I stick to python 2.7 so far. Shall I use python 3?

**Comment by fosterlynn** [comment] 2016-11-21 22:05
No, we are still on 2.7 on all versions.  (Bob will be available in a bit.)

**Comment by bhaugen** [comment] 2016-11-21 22:30
Jc: repeat:
> Since I am unable to reproduce it, I think I would next want to install the repo exactly like you did, and see what happens.

How did you install it? In a virtualenv? Or just cloned into a directory /Workspace/GoPacifia/? 
What is Workspace? 
Also, what operating system?

**Comment by jcgarnier** [comment] 2016-11-23 09:24
I cloned the git master branch in /Workspace/GoPacifia. I'm not using a virtual env or anything. 
The Operating System is Ubuntu 16.04

**Comment by bhaugen** [comment] 2016-11-23 14:40
Jc, would you have time to try again, following the instructions in https://github.com/gopacifia/DEEP/blob/master/docs/install.txt ?

**Comment by jcgarnier** [comment] 2016-11-24 06:27
Hi Bob,

I will try this out from scratch on another machine, and if it works I'll make it an automated script. Do you have any recommendation for a python environment? At work I use gradle for C++ and Java.

**Comment by bhaugen** [comment] 2016-11-24 11:41
Using a virtual environment, you should be able to do it from the same machine without disturbing your global packages. That's what virtualenvs are for.

Unfortunately, I have no experience with automated installations or deployments. @cluttazi in [this comment](https://github.com/gopacifia/DEEP/issues/4#issuecomment-261770647) is thinking of Ansible.

**Comment by jcgarnier** [comment] 2016-11-24 21:23
Following the install.txt file everything works fine. So I'll make this my developmennt environment for now.
I'll check what's different.

ansible is quite good to manage server configurations and application deployments. I use it at work.

I'm maybe a bit too new to python, I would  have expected that an operational deployment is different from a development environment setup, but it seems to be the same in this context :)

**Comment by bhaugen** [comment] 2016-11-25 00:04
Jc, thank you very much for trying again. The operational environment is somewhat different from the dev environment, but we're deploying in virtual environments in both cases.

The differences include:
* using the builtin django server for dev, but apache for ops
* sqlite for dev and test, postgresql for ops
* and probably several others that I am missing since I don't do the ops anymore.

**Comment by bhaugen** [comment] 2016-11-25 12:55
So, can we close this issue again?

**Comment by escanda** [comment] 2017-02-13 08:28
As it is usually said, it works on my pc :)

**Comment by escanda** [comment] 2017-02-25 19:32
@jcgarnier it was due you needed to run `python manage.py migrate` before running the tests. reproduced and fixed on my machine :)

**Closed by escanda** 2017-02-25 19:32 UTC
